### ISSUE TITLE
依存ライブラリをソースコード内に含める必要はあるかどうか

### ISSUE THREAD

**Issue by Lucky3028** [SigureRuri/MorningGlorySeeds#1]
わざわざ本プラグインのソースの中に含めず、依存関係として入れるだけで足りませんか？

**Comment by SigureRuri** [comment]
おっしゃるように、SkyStoryを依存関係に追加してもよいです。
その場合は別途ビルド時にSkyStoryを本プラグインのjarに含めるコードがbuild.gradleに書き足す必要がありますね。
(kotlin-stdlibなんかがそうです。プラグインのソースに含めず依存関係に追加して、ビルド時にプラグインのjarに含めています。)

ソース内に直接含めるとビルド時にSkyStoryもコンパイルして本プラグインのjar内に含めてくれるのでこの方法をとっているだけです。

本質的にはどちらでもよいです！

**Comment by Lucky3028** [comment]
そうですよね、せっかくライブラリを分けているのに含んでしまうとその意味が薄くなってしまうと考えられますので変えてもよろしいですか？

**Comment by SigureRuri** [comment]
はい、お願いします！

**Comment by SigureRuri** [comment]
お願いしますといった矢先申し訳ないですが、今手が空いているので私が変えておきます！
