### ISSUE TITLE
Kotlinの標準ライブラリを生成Jarに含まない理由ってあります？

### ISSUE THREAD

**Issue by Lucky3028** [SigureRuri/MorningGlorySeeds#6]
cf. e6cddfac5ab85f929560375aa7758eec7b10fb89

**Comment by SigureRuri** [comment]
すみません、記載し忘れていたのですが、ライブラリの梱包にgradleのshadowプラグインを使用しているので、ビルド時にはbuildタスクではなくshadowJarタスクを実行してください！
恐らくそれが原因だと思います。

**Comment by Lucky3028** [comment]
なるほど。ありがとうございます、確認します。

**Comment by Lucky3028** [comment]
できました、お騒がせしました
